# Generated by Django 3.1.3 on 2020-11-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201122_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
