# Generated by Django 3.1.3 on 2020-11-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.CharField(default='', max_length=50),
        ),
    ]
