# Generated by Django 3.1.3 on 2020-11-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='medical_condition',
            field=models.CharField(default='', max_length=200),
        ),
    ]
